version: '3.6'
services:
  server:
    hostname: server
    build: 
      context: .
      dockerfile: Dockerfile
    command: --check-caps false
    restart: always
    
    ports: 
      - '41773:1972'
      - '42773:52773'
      - '43773:53773'
    volumes:
      - ./:/opt/irisapp
      
  client:
    hostname: client
    build: 
      context: .
      dockerfile: Dockerfile
    command: --check-caps false
    restart: always
    
    ports: 
      - '41443:1972'
      - '42443:52773'
      - '43443:53773'
    volumes:
      - ./:/opt/irisapp
